version: 1
disable_existing_loggers: False

formatters:
  default:
    "()": colorlog.ColoredFormatter
    format: "%(log_color)s%(asctime)s [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: no

  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [default]
    propagate: no

root:
  level: INFO
  handlers: [default]
